apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tfm-ai-api
  namespace: tfm-ai-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: helmcode
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - tfm-ai-api.helmcode.com
    secretName: tfm-ai-api-tls
  rules:
  - host: tfm-ai-api.helmcode.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tfm-ai-api
            port:
              number: 8000
